### ISSUE TITLE
Set up different types of issue templates

### ISSUE THREAD

**Issue by JazzBrotha** [JazzBrotha/screenmycode#20]
At the moment, there is just one issue template for all issues. Usually, you have one template per type of change (bug, documentation, feature, etc.). Create a folder inside the `.github` folder named `ISSUE_TEMPLATE` where you include the different templates.

See the [Atom repository](https://github.com/atom/atom/tree/master/.github) for inspiration.

**Comment by brianabaker** [comment]
I'd like to claim this!

**Comment by JazzBrotha** [comment]
@brianabaker Nice! All yours.
