### ISSUE TITLE
Set up pull request template

### ISSUE THREAD

**Issue by JazzBrotha** [JazzBrotha/screenmycode#3]
Create a `PULL_REQUEST_TEMPLATE.md` file in the root directory and add content to the document. The body of the document should at least include the following.

- A reference to a related issue in your repository.
- A description of the changes proposed in the pull request.
- @mentions of the person or team responsible for reviewing proposed changes.

You can follow [this guide](https://help.github.com/articles/creating-a-pull-request-template-for-your-repository/) on GitHub Help if you would like.

**Comment by cameo-myob** [comment]
Happy to take this. :)

**Comment by JazzBrotha** [comment]
Big thanks @cameo-myob ! PR is approved and merged. Closing issue.
