### ISSUE TITLE
Improve the contribution guidelines

### ISSUE THREAD

**Issue by JazzBrotha** [JazzBrotha/screenmycode#8]
Suggest any change to improve the [Contribution Guidelines](https://github.com/JazzBrotha/screenmycode/blob/master/CONTRIBUTING.md). The change can include adding new sections, changing headings, syntax reconstruction, etc.

**Comment by jules-kim** [comment]
I can do this. Do you think something's wrong with the current guidelines? Do you have any specific requests for what the changes should look like?

**Comment by JazzBrotha** [comment]
Great! Nothing is wrong with the current guidelines. You are welcomed to suggest any change that you think improves the document.
